# Generated by Django 4.2 on 2025-07-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='materials/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Текущий остаток')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('lack', models.PositiveIntegerField(default=0, verbose_name='Нехватка')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='mebel.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='mebel_categ_name_39079a_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['id', 'slug'], name='mebel_mater_id_6d32b2_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='mebel_mater_name_57a1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-created'], name='mebel_mater_created_ff4c2b_idx'),
        ),
    ]
