# Generated by Django 4.2 on 2025-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='mebel_mater_created_ff4c2b_idx',
        ),
        migrations.RemoveField(
            model_name='material',
            name='available',
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['lack'], name='mebel_mater_lack_804432_idx'),
        ),
    ]
