# Generated by Django 4.2 on 2025-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_materialoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
