# Generated by Django 4.2 on 2025-09-15 19:48

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_alter_material_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Replace('name', models.Value(' '), models.Value(''))), name='unique_normalized_name'),
        ),
    ]
