# Generated by Django 4.2 on 2025-09-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0006_supplier_supplier_mebel_suppl_name_e26785_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supplier',
            name='mebel_suppl_name_e26785_idx',
        ),
    ]
