# Generated by Django 4.2 on 2025-09-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('not_paid', 'Не оплачено'), ('partially_paid', 'Оплачено частично'), ('fully_paid', 'Оплачено полностью')], default='not_paid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
