# Generated by Django 4.2 on 2025-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='written_off',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
