# Generated by Django 4.2 on 2025-09-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_written_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='operation_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
