# Generated by Django 4.2 on 2025-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_operation_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='blueprint',
            field=models.ImageField(blank=True, null=True, upload_to='blueprints/%Y/%m/%d/', verbose_name='Чертеж'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('kitchen', 'Кухня'), ('wardrobe', 'Шкаф'), ('table', 'Стол'), ('bed', 'Кровать'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя заказчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(default=0, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transferred_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Перечисленные средства'),
        ),
        migrations.AddField(
            model_name='order',
            name='visualization',
            field=models.ImageField(blank=True, null=True, upload_to='visualizations/%Y/%m/%d/', verbose_name='Визуализация'),
        ),
    ]
