# Generated by Django 4.2 on 2025-09-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_city_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
