# Generated by Django 4.2 on 2025-09-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='reserved',
        ),
    ]
