# Generated by Django 4.2 on 2025-09-24 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 18, 25, 9, 961555, tzinfo=datetime.timezone.utc), verbose_name='Дата сдачи'),
        ),
    ]
