# Generated by Django 4.2 on 2025-09-24 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installation_status',
            field=models.CharField(choices=[('not_installed', 'Не установлено'), ('installed', 'Установлено')], default='not_installed', max_length=20, verbose_name='Установка'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 19, 28, 15, 250775, tzinfo=datetime.timezone.utc), verbose_name='Дата сдачи'),
        ),
    ]
