# Generated by Django 4.2 on 2025-09-25 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_installation_status_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='installation_photos/%Y/%m/%d/', verbose_name='Фото установки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 9, 26, 17, 29, 42, 747079, tzinfo=datetime.timezone.utc), verbose_name='Дата сдачи'),
        ),
    ]
